/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import model.Address;
import model.Person;
import model.PersonDirectory;
import ui.PersonManager.PersonMngWorkAreaJPanel;

/**
 *
 * @author Vrajesh
 */
public class MainJFrame extends javax.swing.JFrame {
    
    private PersonDirectory personDirectory;

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        
        this.personDirectory = new PersonDirectory();
        generateDemoData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        topJPanel = new javax.swing.JPanel();
        btnPersonProfileManage = new javax.swing.JButton();
        personProfileContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 900));

        jSplitPane1.setDividerLocation(85);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        topJPanel.setBackground(new java.awt.Color(204, 255, 204));

        btnPersonProfileManage.setText("Open Person Profile Work Area");
        btnPersonProfileManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonProfileManageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout topJPanelLayout = new javax.swing.GroupLayout(topJPanel);
        topJPanel.setLayout(topJPanelLayout);
        topJPanelLayout.setHorizontalGroup(
            topJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topJPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnPersonProfileManage)
                .addContainerGap(436, Short.MAX_VALUE))
        );
        topJPanelLayout.setVerticalGroup(
            topJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topJPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnPersonProfileManage)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(topJPanel);

        personProfileContainer.setBackground(new java.awt.Color(255, 204, 204));
        personProfileContainer.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(personProfileContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPersonProfileManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonProfileManageActionPerformed
        // TODO add your handling code here:
        
        // Open Person Manage Work Area when this button is clicked
        PersonMngWorkAreaJPanel panel = new PersonMngWorkAreaJPanel(personProfileContainer, personDirectory);
        personProfileContainer.add("PersonMngWorkAreaJPanel", panel);
        
        // Change the layout to PersonMngWorkAreaPanel
        CardLayout layout = (CardLayout) personProfileContainer.getLayout();
        layout.next(personProfileContainer);
    }//GEN-LAST:event_btnPersonProfileManageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPersonProfileManage;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel personProfileContainer;
    private javax.swing.JPanel topJPanel;
    // End of variables declaration//GEN-END:variables

    private void generateDemoData(){
        Person person1 = personDirectory.addPerson();
        person1.setFirstName("Dhyey");
        person1.setLastName("Rabadiya");
        person1.setSocialSecurityNumber("Social1234");
        person1.setAge(22);
        person1.setGender('M');
        person1.setIsActive(true);
        person1.setHomeAddress(new Address("S Huntington Ave", "2", "Boston", "Masachussets", "02130", 9737677983L));
        person1.setWorkAddress(new Address("Huntington Ave", "2", "Boston", "Masachussets", "02120", 9737677983L));
    
        Person person2 = personDirectory.addPerson();
        person2.setFirstName("Sudhir");
        person2.setLastName("Kakadiya");
        person2.setSocialSecurityNumber("Social1345");
        person2.setAge(30);
        person2.setGender('M');
        person2.setIsActive(true);
        person2.setHomeAddress(new Address("Grove St", "2", "New Jersey", "New York", "03110", 9737666983L));
        person2.setWorkAddress(new Address("47th St", "2", "New York", "New York", "03340", 9737666983L));
        
        Person person3 = personDirectory.addPerson();
        person3.setFirstName("Parth");
        person3.setLastName("Kakadiya");
        person3.setSocialSecurityNumber("Social1456");
        person3.setAge(22);
        person3.setGender('M');
        person3.setIsActive(true);
        person3.setHomeAddress(new Address("Union St", "2", "New Jersey", "New York", "03110", 9737776983L));
        person3.setWorkAddress(new Address("47th St", "2", "New York", "New York", "03340", 9737776983L));
        
        Person person4 = personDirectory.addPerson();
        person4.setFirstName("Tejas");
        person4.setLastName("Shekhda");
        person4.setSocialSecurityNumber("Social1156");
        person4.setAge(22);
        person4.setGender('M');
        person4.setIsActive(false);
        person4.setHomeAddress(new Address("Union Ave", "78", "New Jersey", "New York", "03110", 9732376983L));
        person4.setWorkAddress(new Address("47th St", "2", "New York", "New York", "03340", 9732376983L));
        
        Person person5 = personDirectory.addPerson();
        person5.setFirstName("Manav");
        person5.setLastName("Kheni");
        person5.setSocialSecurityNumber("Social1346");
        person5.setAge(22);
        person5.setGender('M');
        person5.setIsActive(true);
        person5.setHomeAddress(new Address("Jvue Ave", "78", "Boston", "Masachussets", "02112", 8572376983L));
        person5.setWorkAddress(new Address("47th St", "2", "New York", "New York", "02120", 8572376983L));
    }

}
